# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Dec 19 21:02:25 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(362, 206)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.single_line_in = QtGui.QLineEdit(self.tab)
        self.single_line_in.setObjectName(_fromUtf8("single_line_in"))
        self.gridLayout_4.addWidget(self.single_line_in, 0, 1, 1, 1)
        self.btn_single_file = QtGui.QToolButton(self.tab)
        self.btn_single_file.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_single_file.setObjectName(_fromUtf8("btn_single_file"))
        self.gridLayout_4.addWidget(self.btn_single_file, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.single_line_out = QtGui.QLineEdit(self.tab)
        self.single_line_out.setObjectName(_fromUtf8("single_line_out"))
        self.gridLayout_4.addWidget(self.single_line_out, 1, 1, 1, 1)
        self.bt_output_single = QtGui.QToolButton(self.tab)
        self.bt_output_single.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_output_single.setObjectName(_fromUtf8("bt_output_single"))
        self.gridLayout_4.addWidget(self.bt_output_single, 1, 2, 1, 1)
        self.btn_single_convert = QtGui.QPushButton(self.tab)
        self.btn_single_convert.setText(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_single_convert.setObjectName(_fromUtf8("btn_single_convert"))
        self.gridLayout_4.addWidget(self.btn_single_convert, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.btn_dir_lookup = QtGui.QToolButton(self.tab_2)
        self.btn_dir_lookup.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dir_lookup.setObjectName(_fromUtf8("btn_dir_lookup"))
        self.gridLayout_2.addWidget(self.btn_dir_lookup, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Output Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.btn_output_dir = QtGui.QToolButton(self.tab_2)
        self.btn_output_dir.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_output_dir.setObjectName(_fromUtf8("btn_output_dir"))
        self.gridLayout_2.addWidget(self.btn_output_dir, 1, 3, 1, 1)
        self.btn_dir_convert = QtGui.QPushButton(self.tab_2)
        self.btn_dir_convert.setText(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_dir_convert.setObjectName(_fromUtf8("btn_dir_convert"))
        self.gridLayout_2.addWidget(self.btn_dir_convert, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "E&dit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "Options..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionOptions)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.label_5.setBuddy(self.lineEdit)
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.btn_single_file, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.single_locate_file)
        QtCore.QObject.connect(self.bt_output_single, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.single_output_file)
        QtCore.QObject.connect(self.btn_dir_lookup, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.dir_locate)
        QtCore.QObject.connect(self.btn_output_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.dir_output)
        QtCore.QObject.connect(self.btn_single_convert, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.convert)
        QtCore.QObject.connect(self.btn_dir_convert, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.convert_dir)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionOptions, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.spawn_options)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.spawn_about)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.single_line_in)
        MainWindow.setTabOrder(self.single_line_in, self.btn_single_file)
        MainWindow.setTabOrder(self.btn_single_file, self.single_line_out)
        MainWindow.setTabOrder(self.single_line_out, self.bt_output_single)
        MainWindow.setTabOrder(self.bt_output_single, self.btn_single_convert)
        MainWindow.setTabOrder(self.btn_single_convert, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.btn_dir_lookup)
        MainWindow.setTabOrder(self.btn_dir_lookup, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.btn_output_dir)
        MainWindow.setTabOrder(self.btn_output_dir, self.btn_dir_convert)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Single PDF Conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Directory Conversion", None, QtGui.QApplication.UnicodeUTF8))

